### ISSUE TITLE
Discussion: roadmap

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/clesperanto.github.io#1]
Hi @clEsperanto,

first of all thank you all very much for joining this project! This is a first message to see if the communication via github works for all of us. If you answer by liking (or disliking 😉 ) this message, I can see that you get the notifications.

I started writing the clEsperanto roadmap and would be happy about any kind of feedback. I would love to incorporate as many ideas and wishes from you as possible. Only this way this can become a community project. You can also adopt tasks where you would like to be reponsible.
https://github.com/clEsperanto/clesperanto.github.io/blob/master/roadmap.md

You all should have write-access to the document. Please add items you think are important. You can also send pull-requests if you think aspects should be discussed before they become part of the roadmap.

Let's see how this all works. Forming a community around an open-source software project is also new to me. Feels like a new adventure. 🙂 

Thanks for your support!

Cheers,
Robert

**Comment by pr4deepr** [comment]
Hi @haesleinhuepf 
  Excited to be a part of this. 

I am still getting my head around this and I have a few questions/comments.
 
In regard to core development, 
I like the idea of translating ClearCL to Python by exploiting PyOpenCl and/or gputools. I am assuming that this means all other platforms would have to do the same if we went this route.  

However, if ClearCL was translated to C++, is it easier to write wrappers around this in different platforms? Would it be easier to troubleshoot as it will be working from one big common chunk/s of C++ code? Or would it be difficult because, if developers in each platform are not as familiar with C++ code, it will be harder to troubleshoot? Also, how about maintenance and development in the long run?

Again, I am not experienced with software development, so I am happy to hear criticisms/thoughts..

Cheers
Pradeep

**Comment by haesleinhuepf** [comment]
Just for everyone reading this: We're continuing the conversation on image.sc:

https://forum.image.sc/t/clesperanto-development-ideas/35122
